# Generated by Django 4.2 on 2025-07-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_day', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending_1', 'منتظر تایید سرپرست'), ('approved_1', 'تایید توسط سرپرست'), ('rejected_1', 'رد توسط سرپرست'), ('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید مدیر منابع انسانی'), ('approved_3', 'تایید توسط مدیر منابع انسانی'), ('rejected_3', 'رد توسط مدیر منابع انسانی'), ('pending_4', 'منتظر تایید مدیر'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست مرخصی',
                'verbose_name_plural': 'درخواست\u200cهای مرخصی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Leave_Request',
        ),
    ]
