# Generated by Django 4.2 on 2025-07-03 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr.models.define_user


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Define_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=100)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('detail_identity', models.ImageField(blank=True, null=True, upload_to=hr.models.define_user.upload_to_phone_number)),
                ('phone_number', models.CharField(max_length=11)),
                ('id_card', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('couple', models.BooleanField(default=False)),
                ('baby_count', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50)),
                ('password_created_at', models.DateTimeField(auto_now_add=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('human_resources', 'مدیر منابع انسانی'), ('department_manager', 'مدیر بخش'), ('supervisor', 'سرپرست'), ('employee', 'کارمند')], default='employee', max_length=30)),
                ('department', models.CharField(choices=[(1, 'مدیر سیستم'), (2, 'مدیریت'), (3, 'سایت'), (4, 'آی تی'), (5, 'منابع انسانی'), (6, 'مالی'), (7, 'پشتیبانی'), (8, 'فروش'), (9, 'اداری'), (10, 'حضوری'), (11, 'محتوا')], max_length=35)),
                ('checkpoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(choices=[('blow', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('diploma_p', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('bachelor_p', 'فوق لیسانس'), ('phd', 'دکتری'), ('phd_p', 'فوق دکتری')], default='blow', max_length=25)),
                ('study_field', models.CharField(max_length=255)),
                ('interesting', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('review', 'درحال بررسی'), ('reject', 'عدم تایید'), ('accept', 'تایید')], default='review', max_length=20)),
                ('checkpoint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('department', models.ManyToManyField(related_name='suggestions', to='accounts.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(verbose_name='start_day')),
                ('start_hour', models.TimeField(blank=True, default=datetime.time(9, 30), verbose_name='start_hour')),
                ('end_day', models.DateField(verbose_name='end_day')),
                ('end_hour', models.TimeField(blank=True, default=datetime.time(17, 30), null=True, verbose_name='end_hour')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید منابع انسانی'), ('approved_3', 'تایید توسط منابع انسانی'), ('rejected_3', 'رد توسط منابع انسانی'), ('pending_4', 'منتظر تایید مدیر کل'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_2', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LeaveRequest',
                'verbose_name_plural': 'LeaveRequests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advancehr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending_1', 'منتظر تایید مدیر بخش'), ('approved_1', 'تایید توسط مدیر بخش'), ('rejected_1', 'رد توسط مدیر بخش'), ('pending_2', 'منتظر تایید مدیر منابع انسانی'), ('approved_2', 'تایید توسط مدیر منابع انسانی'), ('rejected_2', 'رد توسط مدیر منابع انسانی'), ('pending_3', 'منتظر تایید مالی'), ('approved_3', 'تایید توسط مالی'), ('rejected_3', 'رد توسط مدیر مالی'), ('pending_4', 'منتظر تایید مدیر'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=35)),
                ('department_manager_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('human_resources_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
