# Generated by Django 4.2 on 2025-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leaverequest_delete_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='remaining_leave_days',
            field=models.PositiveIntegerField(default=2, verbose_name='مانده مرخصی'),
        ),
    ]
