# Generated by Django 4.2 on 2025-07-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_advancehr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancehr',
            name='status',
            field=models.CharField(choices=[('pending_1', 'منتظر تایید مدیر بخش'), ('approved_1', 'تایید توسط مدیر بخش'), ('rejected_1', 'رد توسط مدیر بخش'), ('pending_2', 'منتظر تایید مدیر منابع انسانی'), ('approved_2', 'تایید توسط مدیر منابع انسانی'), ('rejected_2', 'رد توسط مدیر منابع انسانی'), ('pending_3', 'منتظر تایید مالی'), ('approved_3', 'تایید توسط مالی'), ('rejected_3', 'رد توسط مدیر مالی'), ('pending_4', 'منتظر تایید مدیر'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=35),
        ),
    ]
