# Generated by Django 4.2 on 2025-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_advancehr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=35)),
                ('education', models.CharField(choices=[('blow', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('diploma_p', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('bachelor_p', 'فوق لیسانس'), ('phd', 'دکتری'), ('phd_p', 'فوق دکتری')], default='blow', max_length=25)),
                ('study_field', models.CharField(max_length=255)),
                ('interesting', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('checkpoint', models.BooleanField(default=False)),
            ],
        ),
    ]
