# Generated by Django 4.2 on 2025-07-01 19:59

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'LeaveRequest', 'verbose_name_plural': 'LeaveRequests'},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='remaining_leave_days',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='End Hour'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='start_hour'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_day',
            field=django_jalali.db.models.jDateField(verbose_name='end_day'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_day',
            field=django_jalali.db.models.jDateField(verbose_name='start_day'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_1', 'منتظر تایید سرپرست'), ('approved_1', 'تایید توسط سرپرست'), ('rejected_1', 'رد توسط سرپرست'), ('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید منابع انسانی'), ('approved_3', 'تایید توسط منابع انسانی'), ('rejected_3', 'رد توسط منابع انسانی'), ('pending_4', 'منتظر تایید مدیر کل'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=20),
        ),
    ]
