# Generated by Django 4.2 on 2025-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Define_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=100)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('start_day', models.DateField(blank=True, null=True)),
                ('detail_identity', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=50)),
                ('checkpoint', models.BooleanField(default=False)),
            ],
        ),
    ]
