# Generated by Django 4.2 on 2025-07-02 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_hour',
            field=models.TimeField(blank=True, default=datetime.time(17, 30), null=True, verbose_name='End Hour'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_hour',
            field=models.TimeField(blank=True, default=datetime.time(9, 30), verbose_name='start_hour'),
        ),
    ]
