# Generated by Django 4.2 on 2025-07-02 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_leaverequest_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_day',
            field=models.DateField(verbose_name='end_day'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_hour',
            field=models.TimeField(blank=True, default=datetime.time(17, 30), null=True, verbose_name='end_hour'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_day',
            field=models.DateField(verbose_name='start_day'),
        ),
    ]
