# Generated by Django 4.2 on 2025-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_define_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('review', 'درحال بررسی'), ('reject', 'عدم تایید'), ('accept', 'تایید')], default='review', max_length=20),
        ),
    ]
