# Generated by Django 5.2 on 2025-07-02 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 7, 2, 3, 36, 45, 850417, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
    ]
