# Generated by Django 4.2 on 2025-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_remaining_leave_days'),
        ('hr', '0007_alter_leaverequest_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='department',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='department',
            field=models.ManyToManyField(related_name='suggestions', to='accounts.department'),
        ),
    ]
