# Generated by Django 4.2 on 2025-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_suggestion_department_suggestion_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Suggestion', 'verbose_name_plural': 'Suggestions'},
        ),
        migrations.AddField(
            model_name='suggestion',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
