# Generated by Django 4.2 on 2025-07-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_remove_resume_username_resume_password_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='username',
        ),
    ]
