# Generated by Django 4.2 on 2025-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_leaverequest_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_2', 'منتظر تایید مدیر بخش'), ('approved_2', 'تایید توسط مدیر بخش'), ('rejected_2', 'رد توسط مدیر بخش'), ('pending_3', 'منتظر تایید منابع انسانی'), ('approved_3', 'تایید توسط منابع انسانی'), ('rejected_3', 'رد توسط منابع انسانی'), ('pending_4', 'منتظر تایید مدیر کل'), ('approved_4', 'تایید نهایی'), ('rejected_4', 'رد نهایی')], default='pending_1', max_length=20),
        ),
    ]
