# Generated by Django 4.2 on 2025-07-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_resume_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='username',
        ),
    ]
