# Generated by Django 4.2 on 2025-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_remove_resume_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='password_created_at',
        ),
        migrations.AddField(
            model_name='define_user',
            name='password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
