# Generated by Django 4.2 on 2025-07-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0013_remove_resume_password_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='define_user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
    ]
