# Generated by Django 4.2 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_define_user_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define_user',
            name='password_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
