# Generated by Django 4.2 on 2025-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_define_user_baby_count_define_user_couple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancehr',
            name='admin_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancehr',
            name='department_manager_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancehr',
            name='human_resources_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advancehr',
            name='supervisor_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
