# Generated by Django 4.2 on 2025-07-02 13:06

from django.db import migrations, models
import hr.models.define_user


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_advancehr_admin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='define_user',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='define_user',
            name='detail_identity',
            field=models.ImageField(blank=True, null=True, upload_to=hr.models.define_user.upload_to_phone_number),
        ),
    ]
