# Generated by Django 4.2 on 2025-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_define_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define_user',
            name='department',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('site', 'سایت'), ('it', 'آی تی'), ('human_resources', 'منابع انسانی'), ('finance', 'مالی'), ('support', 'پشتیبانی'), ('sales', 'فروش'), ('administrative', 'اداری'), ('formal', 'حضوری'), ('content', 'محتوا')], default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='define_user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('human_resources', 'مدیر منابع انسانی'), ('department_manager', 'مدیر بخش'), ('supervisor', 'سرپرست'), ('employee', 'کارمند')], default='employee', max_length=30),
        ),
    ]
