# Generated by Django 4.2 on 2025-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_define_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define_user',
            name='department',
            field=models.CharField(choices=[(1, 'مدیر سیستم'), (2, 'مدیریت'), (3, 'سایت'), (4, 'آی تی'), (5, 'منابع انسانی'), (6, 'مالی'), (7, 'پشتیبانی'), (8, 'فروش'), (9, 'اداری'), (10, 'حضوری'), (11, 'محتوا')], max_length=35),
        ),
        migrations.AlterField(
            model_name='define_user',
            name='user_role',
            field=models.CharField(choices=[(1, 'مدیر سیستم'), (2, 'مدیریت'), (3, 'مدیر منابع انسانی'), (4, 'مدیر بخش'), (5, 'سرپرست'), (6, 'کارمند')], default='employee', max_length=30),
        ),
    ]
