# Generated by Django 4.2 on 2025-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_define_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define_user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیریت'), ('human_resources', 'مدیر منابع انسانی'), ('department_manager', 'مدیر بخش'), ('supervisor', 'سرپرست'), ('employee', 'کارمند')], default='employee', max_length=30),
        ),
    ]
