# Generated by Django 4.2 on 2025-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_leave_days',
            field=models.PositiveIntegerField(default=30, verbose_name='مانده مرخصی'),
        ),
    ]
