# Generated by Django 4.2 on 2025-07-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_remaining_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remaining_leave_days',
        ),
    ]
